feedback: true
device: cuda
data_dir: ./data/iemocap_data.pkl
results_dir: /home/egeorgiou/experimental/mm/slp/results_iemocap/sum_rnn_feedback_attrnn_4medium_all
train: true
test: true
overfit_batch: false
debug: false
remove_pauses: true

normalize_audio: false
normalize_visual: false

modalities:
    - text
    - glove
    - audio
    - visual

modalities:
    - text
    - glove
    - audio
    - visual

audio:
    model:
        input_size: 74
        hidden_size: 60
        layers: 4
        dropout: !!float 0.2
        bidirectional: true
        rnn_type: lstm
        attention: true
        return_hidden: false
        batchnorm: false

visual:
    model:
        input_size: 35
        hidden_size: 60
        layers: 4
        dropout: !!float 0.2
        bidirectional: true
        rnn_type: lstm
        attention: true
        return_hidden: false
        batchnorm: false

text:
    model:
        input_size: 300
        hidden_size: 100
        layers: 4
        dropout: !!float 0.2
        bidirectional: true
        rnn_type: lstm
        attention: true
        return_hidden: false

fuse:
    method: attrnn
    modality_weights: false
    projection_size: 100
    use_mask: false
    model_dim: 100
    projection_type: null
    layers: 1
    all_modalities: true
    residual: 0
    mmdrop: !!float 0.0
    self_feedback: false
    feedback_type: sum_rnn

experiment:
    name: iemocap-binary-audio-text-visual
    description: IEMOCAP

dataloaders:
    batch_size: 32
    num_workers: 1
    pin_memory: false

optimizer:
    name: Adam
    learning_rate: !!float 5e-4

trainer:
    patience: 10
    max_epochs: 100
    retain_graph: true
    load_model: iemocap-binary-audio-text-visual_checkpoint.best.pth
    checkpoint_dir: /home/egeorgiou/experimental/mm/slp/checkpoints-sum-rnn-feedback-attrnn-iemo_4medium_all
