language: python
sudo: required
python:
        - "3.6"
before_install:
    - pip install -U pip
    - pip install mypy
    - pip install flake8
    - pip install .
install:
    - pip install --progress-bar off -r requirements.txt
script:
    - python -m flake8 slp
    - python -m flake8 examples
    - python -m mypy slp
    - python -m mypy examples
    - pytest -s tests
