language: python
sudo: required
dist: 'focal'

python:
    - "3.8"

before_install:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install .
script:
    - nox -s lintci typecheckci testsci
