name: slp CI - Check linting, types and run tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  run-nox:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]
    name: Check linting, types and unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install .
      - name: Lint
        run: nox -s lintci
      - name: Typecheck
        run: nox -s typecheckci
      - name: Test
        run: nox -s testsci
      - name: Deploy Docs
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          mkdocs gh-deploy --config-file ${GITHUB_WORKSPACE}/mkdocs.yml --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
